# Generated by Django 4.1.5 on 2023-01-11 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmodel',
            name='eating_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 19, 18, 58, 540210)),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='pet_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 19, 18, 58, 540210)),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='sleep_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 19, 18, 58, 540210)),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='water_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 19, 18, 58, 540210)),
        ),
    ]
