# Generated by Django 4.1.5 on 2023-01-24 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0006_alter_petmodel_eating_time_alter_petmodel_pet_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmodel',
            name='eating_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 12, 1, 55, 643425)),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='happiness_level',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='hunger_level',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='pet_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 12, 1, 55, 643425)),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='sleep_level',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='sleep_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 12, 1, 55, 643425)),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='water_level',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='water_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 12, 1, 55, 643425)),
        ),
    ]
